// src/domain/edges.ts
import type { Edge } from './types'

export const EDGES: Edge[] = [
  // build
  { id: 'e-src-swc', from: 'src-dashboard-nav', to: 'swc', kind: 'transform', label: 'compile' },
  { id: 'e-swc-bundler', from: 'swc', to: 'bundler', kind: 'data', label: 'transformed module' },
  { id: 'e-bundler-layers', from: 'bundler', to: 'layers', kind: 'control', label: 'assign layer' },
  { id: 'e-bundler-browser-chunks', from: 'bundler', to: 'browser-chunks', kind: 'transform', label: 'pack' },
  { id: 'e-bundler-server-chunks', from: 'bundler', to: 'server-chunks', kind: 'transform', label: 'pack' },
  { id: 'e-bundler-crm', from: 'bundler', to: 'client-reference-manifest', kind: 'transform', label: 'write references' },
  { id: 'e-route-analysis-prerender', from: 'route-analysis', to: 'prerender', kind: 'control', label: 'static routes' },
  { id: 'e-prerender-outputs', from: 'prerender', to: 'prerendered-outputs', kind: 'transform', label: 'html · rsc · shell' },
  { id: 'e-outputs-server-cache', from: 'prerendered-outputs', to: 'server-cache', kind: 'data', label: 'seed' },
  // ---------- Production build (J1) ----------
  { id: 'e-build-discovery', from: 'next-build', to: 'route-discovery', kind: 'control', label: 'walk app/ · pages/' },
  { id: 'e-discovery-routes-manifest', from: 'route-discovery', to: 'routes-manifest', kind: 'transform', label: 'route map' },
  { id: 'e-discovery-loader', from: 'route-discovery', to: 'loader-tree', kind: 'data', label: 'loader tree' },
  { id: 'e-discovery-bundler', from: 'route-discovery', to: 'bundler', kind: 'data', label: 'entrypoints' },
  { id: 'e-form-compile', from: 'src-profile-form', to: 'swc', kind: 'transform', label: 'compile' },
  { id: 'e-bundler-client-entry', from: 'bundler', to: 'flight-client-entry-plugin', kind: 'control', label: 'graph per server entry' },
  { id: 'e-client-entry-split', from: 'flight-client-entry-plugin', to: 'split-chunks', kind: 'data', label: 'browser entry' },
  { id: 'e-split-browser-chunks', from: 'split-chunks', to: 'browser-chunks', kind: 'transform', label: 'framework · lib · route' },
  { id: 'e-split-flight-manifest', from: 'split-chunks', to: 'flight-manifest-plugin', kind: 'data', label: 'chunk names' },
  { id: 'e-flight-manifest-crm', from: 'flight-manifest-plugin', to: 'client-reference-manifest', kind: 'transform', label: 'write row' },
  { id: 'e-pages-manifest-chunks', from: 'pages-manifest', to: 'server-chunks', kind: 'lookup', label: 'route → module' },
  { id: 'e-build-manifest-html', from: 'build-manifest', to: 'html', kind: 'lookup', label: 'script tags' },
  { id: 'e-prerender-manifest-cache', from: 'prerender-manifest', to: 'server-cache', kind: 'lookup', label: 'revalidate · fallback' },
  { id: 'e-middleware-manifest-proxy', from: 'middleware-manifest', to: 'proxy', kind: 'lookup', label: 'matchers' },
  { id: 'e-bundler-route-analysis', from: 'bundler', to: 'route-analysis', kind: 'data', label: 'route modules' },
  { id: 'e-analysis-prerender-manifest', from: 'route-analysis', to: 'prerender-manifest', kind: 'transform', label: 'strategy per route' },
  { id: 'e-server-chunks-tracing', from: 'server-chunks', to: 'tracing', kind: 'data', label: 'server entries' },
  { id: 'e-tracing-standalone', from: 'tracing', to: 'standalone', kind: 'transform', label: '.nft.json → copy' },
  { id: 'e-analysis-summary', from: 'route-analysis', to: 'next-build', kind: 'data', label: '○ ● ƒ tree' },
  // request
  { id: 'e-http-ladder', from: 'node-http', to: 'routing-ladder', kind: 'control', label: 'request' },
  { id: 'e-custom-ladder', from: 'custom-server', to: 'routing-ladder', kind: 'control', label: 'handle()' },
  { id: 'e-custom-handle', from: 'custom-server', to: 'custom-handle', kind: 'control', label: 'handle()' },
  { id: 'e-handle-ladder', from: 'custom-handle', to: 'routing-ladder', kind: 'control', label: 'same ladder' },
  { id: 'e-custom-healthz', from: 'custom-server', to: 'custom-healthz', kind: 'data' },
  { id: 'e-tracing-custom-server', from: 'tracing', to: 'custom-server', kind: 'lookup', label: 'not traced' },
  { id: 'e-manifest-ladder', from: 'routes-manifest', to: 'routing-ladder', kind: 'lookup', label: 'loaded at startup' },
  { id: 'e-ladder-proxy', from: 'routing-ladder', to: 'proxy', kind: 'control', label: 'step 3' },
  { id: 'e-ladder-exits', from: 'routing-ladder', to: 'early-exits', kind: 'control', label: 'step 5' },
  { id: 'e-ladder-loader', from: 'routing-ladder', to: 'loader-tree', kind: 'control', label: 'handoff' },
  { id: 'e-server-chunks-loader', from: 'server-chunks', to: 'loader-tree', kind: 'lookup', label: 'require' },
  { id: 'e-server-cache-html', from: 'server-cache', to: 'html', kind: 'data', label: 'cached HTML + RSC' },
  { id: 'e-loader-rsc', from: 'loader-tree', to: 'rsc-runtime-entity', kind: 'data', label: 'segments' },
  { id: 'e-db-rsc', from: 'db', to: 'rsc-runtime-entity', kind: 'data', label: 'data' },
  { id: 'e-crm-rsc', from: 'client-reference-manifest', to: 'rsc-runtime-entity', kind: 'lookup', label: 'ref lookup' },
  { id: 'e-rsc-flight', from: 'rsc-runtime-entity', to: 'flight', kind: 'transform', label: 'serialize' },
  { id: 'e-flight-tee', from: 'flight', to: 'flight-tee', kind: 'tee', label: 'tee' },
  { id: 'e-tee-ssr', from: 'flight-tee', to: 'ssr-runtime-entity', kind: 'data', label: 'copy 1' },
  { id: 'e-tee-nextf', from: 'flight-tee', to: 'next-f', kind: 'data', label: 'copy 2 · inline', crossing: 'data+refs' },
  { id: 'e-ssr-html', from: 'ssr-runtime-entity', to: 'html', kind: 'transform', label: 'render HTML' },
  { id: 'e-html-dom', from: 'html', to: 'dom', kind: 'data', label: 'document', crossing: 'data' },
  { id: 'e-chunks-client', from: 'browser-chunks', to: 'client-components', kind: 'data', label: 'script', crossing: 'code' },
  { id: 'e-nextf-react', from: 'next-f', to: 'react-client', kind: 'transform', label: 'reconstruct' },
  { id: 'e-react-client-components', from: 'react-client', to: 'client-components', kind: 'control', label: 'hydrate' },
  { id: 'e-react-router', from: 'react-client', to: 'app-router', kind: 'data', label: 'seed router state' },
  { id: 'e-router-tree', from: 'app-router', to: 'router-state-tree', kind: 'data', label: 'owns' },
  { id: 'e-tree-loader', from: 'router-state-tree', to: 'loader-tree', kind: 'data', label: 'Next-Router-State-Tree', crossing: 'data' },
  { id: 'e-flight-router-patch', from: 'flight', to: 'app-router', kind: 'data', label: 'Flight patch', crossing: 'data' },
  { id: 'e-scheduler-segment-cache', from: 'prefetch-scheduler', to: 'segment-cache', kind: 'control', label: 'fill' },
  { id: 'e-client-action', from: 'client-components', to: 'action-handler', kind: 'data', label: 'POST Next-Action', crossing: 'data' },
  { id: 'e-action-db', from: 'action-handler', to: 'db', kind: 'data', label: 'mutate' },
  { id: 'e-action-data-cache', from: 'action-handler', to: 'data-cache', kind: 'control', label: 'updateTag' },
  { id: 'e-loader-layout-router', from: 'loader-tree', to: 'layout-router', kind: 'control', label: 'wraps each child' },
  { id: 'e-flight-slices', from: 'flight', to: 'segment-slices', kind: 'data', label: 'sliced per segment' },
  { id: 'e-html-suspense', from: 'html', to: 'suspense-hole', kind: 'data', label: 'late chunk', crossing: 'data' },
  { id: 'e-suspense-client', from: 'suspense-hole', to: 'react-client', kind: 'control', label: 'selective hydration' },
  // ---------- Request routing (J2) ----------
  { id: 'e-http-queue', from: 'node-http', to: 'request-queue', kind: 'control' },
  { id: 'e-queue-ladder', from: 'request-queue', to: 'routing-ladder', kind: 'control', label: 'released after init' },
  { id: 'e-public-ladder', from: 'public-dir', to: 'routing-ladder', kind: 'lookup', label: 'file listing' },
  { id: 'e-ladder-headers', from: 'routing-ladder', to: 'rung-headers', kind: 'control', label: 'step 1' },
  { id: 'e-headers-redirects', from: 'rung-headers', to: 'rung-redirects', kind: 'control' },
  { id: 'e-redirects-proxy', from: 'rung-redirects', to: 'proxy', kind: 'control' },
  { id: 'e-proxy-before-files', from: 'proxy', to: 'rung-before-files', kind: 'control' },
  { id: 'e-before-files-filesystem', from: 'rung-before-files', to: 'rung-filesystem', kind: 'control' },
  { id: 'e-filesystem-after-files', from: 'rung-filesystem', to: 'rung-after-files', kind: 'control' },
  { id: 'e-after-files-dynamic', from: 'rung-after-files', to: 'rung-dynamic', kind: 'control' },
  { id: 'e-dynamic-fallback', from: 'rung-dynamic', to: 'rung-fallback', kind: 'control' },
  { id: 'e-filesystem-loader', from: 'rung-filesystem', to: 'loader-tree', kind: 'control', label: 'handoff: path + params' },
  { id: 'e-loader-after-files', from: 'loader-tree', to: 'rung-after-files', kind: 'lookup' },
  { id: 'e-filesystem-exits', from: 'rung-filesystem', to: 'early-exits', kind: 'control' },
  { id: 'e-chunks-exits', from: 'browser-chunks', to: 'early-exits', kind: 'data', label: '.next/static/chunks' },
  { id: 'e-public-exits', from: 'public-dir', to: 'early-exits', kind: 'data', label: 'public/logo.svg' },
  { id: 'e-filesystem-image', from: 'rung-filesystem', to: 'image-optimizer', kind: 'control' },
  { id: 'e-image-cache', from: 'image-optimizer', to: 'image-cache', kind: 'data', label: 'url · w · q · format' },
  { id: 'e-filesystem-route-handler', from: 'rung-filesystem', to: 'route-handler', kind: 'control', label: 'handler route' },
  // dev
  { id: 'e-dev-parent-child', from: 'dev-parent', to: 'dev-child', kind: 'supervision', label: 'supervise · restart' },
  { id: 'e-dev-child-bundler', from: 'dev-child', to: 'bundler', kind: 'dev', label: 'embedded' },
  { id: 'e-dev-watcher-ladder', from: 'dev-watcher', to: 'routing-ladder', kind: 'dev', label: 'live route map' },
  { id: 'e-dev-hmr-refresh', from: 'dev-hmr', to: 'dev-fast-refresh', kind: 'dev', label: 'client change' },
  { id: 'e-dev-hmr-router', from: 'dev-hmr', to: 'app-router', kind: 'dev', label: 'server change → hmrRefresh()', crossing: 'data' },

  // ---------- Development mode (J9) ----------
  { id: 'e-dev-child-exit', from: 'dev-child', to: 'dev-parent', kind: 'supervision', label: 'exit code: config changed' },
  { id: 'e-dev-child-workers', from: 'dev-child', to: 'dev-static-workers', kind: 'supervision', label: 'spawn per call' },
  { id: 'e-dev-child-turbopack', from: 'dev-child', to: 'dev-turbopack', kind: 'dev', label: 'embedded (default)' },
  { id: 'e-dev-nav-watcher', from: 'src-dashboard-nav', to: 'dev-watcher', kind: 'dev', label: 'save' },
  { id: 'e-dev-summary-watcher', from: 'src-account-summary', to: 'dev-watcher', kind: 'dev', label: 'save' },
  { id: 'e-dev-watcher-turbopack', from: 'dev-watcher', to: 'dev-turbopack', kind: 'dev', label: 'changed file → dirty tasks' },
  { id: 'e-dev-ladder-entries', from: 'routing-ladder', to: 'dev-entries', kind: 'dev', label: 'ensure page compiled' },
  { id: 'e-dev-eviction-entries', from: 'dev-eviction', to: 'dev-entries', kind: 'control', label: 'dispose idle' },
  { id: 'e-dev-hmr-entries', from: 'dev-hmr', to: 'dev-entries', kind: 'dev', label: 'ping keeps alive' },
  { id: 'e-dev-ladder-hmr', from: 'routing-ladder', to: 'dev-hmr', kind: 'dev', label: 'upgrade /_next/hmr' },
  { id: 'e-dev-hmr-client', from: 'dev-hmr', to: 'dev-hmr-client', kind: 'dev', label: 'messages' },
  { id: 'e-dev-turbopack-hmr', from: 'dev-turbopack', to: 'dev-hmr', kind: 'dev', label: 'built · change class' },
  { id: 'e-dev-turbopack-server-chunks', from: 'dev-turbopack', to: 'server-chunks', kind: 'transform', label: 'replace server chunk' },
  { id: 'e-dev-turbopack-browser-chunks', from: 'dev-turbopack', to: 'browser-chunks', kind: 'transform', label: 'update browser chunk' },
  { id: 'e-dev-module-cache-rsc', from: 'dev-module-cache', to: 'rsc-runtime-entity', kind: 'dev', label: 'cleared → fresh require' },
  { id: 'e-dev-client-refresh', from: 'dev-hmr-client', to: 'dev-fast-refresh', kind: 'dev', label: 'client change' },
  { id: 'e-dev-refresh-components', from: 'dev-fast-refresh', to: 'client-components', kind: 'dev', label: 'swap implementation', crossing: 'code' },
  { id: 'e-dev-client-router', from: 'dev-hmr-client', to: 'app-router', kind: 'dev', label: 'server change → refresh', crossing: 'data' },
  { id: 'e-dev-custom-upgrade', from: 'custom-server', to: 'dev-hmr', kind: 'dev', label: 'forward upgrade' },

  // ---------- Navigation (J6) ----------
  { id: 'e-client-scheduler', from: 'client-components', to: 'prefetch-scheduler', kind: 'control', label: '<Link> in viewport / hover' },
  { id: 'e-scheduler-ladder', from: 'prefetch-scheduler', to: 'routing-ladder', kind: 'data', label: 'GET + RSC: 1 + Next-Router-Prefetch: 1', crossing: 'data' },
  { id: 'e-scheduler-route-cache', from: 'prefetch-scheduler', to: 'route-cache', kind: 'control', label: '/_tree response' },
  { id: 'e-router-ladder', from: 'app-router', to: 'routing-ladder', kind: 'data', label: 'GET + RSC: 1 + Next-Router-State-Tree', crossing: 'data' },
  { id: 'e-route-cache-router', from: 'route-cache', to: 'app-router', kind: 'data', label: 'tree on click' },
  { id: 'e-segment-cache-router', from: 'segment-cache', to: 'app-router', kind: 'data', label: 'cached segments' },
  { id: 'e-flight-segment-cache', from: 'flight', to: 'segment-cache', kind: 'data', label: 'prefetched segments', crossing: 'data' },

  // ---------- Server Actions (J7) ----------
  { id: 'e-actions-swc', from: 'src-actions', to: 'swc', kind: 'transform', label: '"use server"' },
  { id: 'e-bundler-srm', from: 'bundler', to: 'server-reference-manifest', kind: 'transform', label: 'action IDs' },
  { id: 'e-form-swc', from: 'src-profile-form', to: 'swc', kind: 'transform', label: 'import → reference' },
  { id: 'e-ladder-action', from: 'routing-ladder', to: 'action-handler', kind: 'control', label: 'POST + Next-Action' },
  { id: 'e-srm-action', from: 'server-reference-manifest', to: 'action-handler', kind: 'lookup', label: 'ID → module' },
  { id: 'e-action-rsc', from: 'action-handler', to: 'rsc-runtime-entity', kind: 'control', label: 're-render if invalidated' },
  { id: 'e-action-flight', from: 'action-handler', to: 'flight', kind: 'transform', label: 'a + f' },
  { id: 'e-data-cache-rsc', from: 'data-cache', to: 'rsc-runtime-entity', kind: 'data', label: 'cache reads' },
  { id: 'e-action-server-cache', from: 'action-handler', to: 'server-cache', kind: 'control', label: 'updateTag / revalidatePath' },

  // ---------- Caching, ISR, PPR (J8) ----------
  { id: 'e-memo-rsc', from: 'request-memo', to: 'rsc-runtime-entity', kind: 'data', label: 'one execution' },
  { id: 'e-db-data-cache', from: 'db', to: 'data-cache', kind: 'data', label: 'miss → fill' },
  { id: 'e-ladder-pages', from: 'routing-ladder', to: 'pages-renderer', kind: 'control', label: 'handoff /posts/7' },
  { id: 'e-pages-server-cache', from: 'pages-renderer', to: 'server-cache', kind: 'lookup', label: 'lookup /posts/7' },
  { id: 'e-pages-regen', from: 'pages-renderer', to: 'isr-regeneration', kind: 'control' },
  { id: 'e-regen-server-cache', from: 'isr-regeneration', to: 'server-cache', kind: 'transform', label: 'replace entry' },
  { id: 'e-db-pages', from: 'db', to: 'pages-renderer', kind: 'data' },
  { id: 'e-pages-html', from: 'pages-renderer', to: 'html', kind: 'transform', label: 'render HTML' },
  { id: 'e-pages-store', from: 'pages-renderer', to: 'server-cache', kind: 'transform', label: 'store · revalidate 60' },
  { id: 'e-server-cache-dir', from: 'server-cache', to: 'next-cache-dir', kind: 'data', label: 'default store' },
  { id: 'e-image-cache-dir', from: 'image-cache', to: 'next-cache-dir', kind: 'data', label: 'images/' },
  { id: 'e-bundler-cache-dir', from: 'bundler', to: 'next-cache-dir', kind: 'data', label: 'persistent cache' },
  { id: 'e-prerender-ppr', from: 'prerender', to: 'ppr-shell', kind: 'transform', label: 'stop at Suspense' },
  { id: 'e-ppr-server-cache', from: 'ppr-shell', to: 'server-cache', kind: 'data', label: 'stored like a static route' },
  { id: 'e-ppr-resume', from: 'ppr-shell', to: 'rsc-runtime-entity', kind: 'control', label: 'resume · real cookies' },

  // ---------- Pages Router initial request (J3) ----------
  { id: 'e-dynamic-pages', from: 'rung-dynamic', to: 'pages-renderer', kind: 'control', label: 'handoff /products/42 · id=42' },
  { id: 'e-pages-manifest-renderer', from: 'pages-manifest', to: 'pages-renderer', kind: 'lookup', label: 'route → module' },
  { id: 'e-pages-gssp', from: 'pages-renderer', to: 'gssp', kind: 'control', label: 'run with req · res · params' },
  { id: 'e-db-gssp', from: 'db', to: 'gssp', kind: 'data', label: 'product 42' },
  { id: 'e-gssp-chunks-strip', from: 'gssp', to: 'browser-chunks', kind: 'control', label: '✂ not in the browser chunk' },
  { id: 'e-pages-gip', from: 'pages-renderer', to: 'gip', kind: 'control', label: 'first load: run on the server' },
  { id: 'e-gip-chunks', from: 'gip', to: 'browser-chunks', kind: 'data', label: 'bundled into the page chunk' },
  { id: 'e-pages-ssr', from: 'pages-renderer', to: 'ssr-runtime-entity', kind: 'transform', label: '<App Component pageProps>' },
  { id: 'e-document-html', from: 'pages-document', to: 'html', kind: 'transform', label: '<Main/> + <NextScript/>' },
  { id: 'e-build-manifest-document', from: 'build-manifest', to: 'pages-document', kind: 'lookup', label: 'script tags' },
  { id: 'e-html-next-data', from: 'html', to: 'next-data', kind: 'data', label: 'props again', crossing: 'data' },
  { id: 'e-chunks-pages-app', from: 'browser-chunks', to: 'pages-app', kind: 'data', label: '_app chunk', crossing: 'code' },
  { id: 'e-chunks-product-page', from: 'browser-chunks', to: 'pages-product-page', kind: 'data', label: 'whole page tree', crossing: 'code' },
  { id: 'e-next-data-react', from: 'next-data', to: 'react-client', kind: 'data', label: 'pageProps' },
  { id: 'e-react-pages-app', from: 'react-client', to: 'pages-app', kind: 'control', label: 'hydrate' },
  { id: 'e-pages-app-product', from: 'pages-app', to: 'pages-product-page', kind: 'data', label: 'Component + pageProps' },
  { id: 'e-pages-router-product', from: 'pages-router', to: 'pages-product-page', kind: 'data', label: 'router.query' },

  // ---------- Pages Router navigation (J4) ----------
  { id: 'e-product-prefetch', from: 'pages-product-page', to: 'pages-prefetch', kind: 'control', label: '<Link> in viewport / hover' },
  { id: 'e-chunks-prefetch', from: 'browser-chunks', to: 'pages-prefetch', kind: 'data', label: 'posts/[id] chunk', crossing: 'code' },
  { id: 'e-prefetch-endpoint', from: 'pages-prefetch', to: 'pages-data-endpoint', kind: 'data', label: 'GET posts/7.json', crossing: 'data' },
  { id: 'e-pages-router-ladder', from: 'pages-router', to: 'routing-ladder', kind: 'data', label: 'GET /_next/data/k7Qm2xLp9/…json', crossing: 'data' },
  { id: 'e-ladder-data-endpoint', from: 'routing-ladder', to: 'pages-data-endpoint', kind: 'control', label: 'data route' },
  { id: 'e-endpoint-gssp', from: 'pages-data-endpoint', to: 'gssp', kind: 'control', label: 'run getServerSideProps' },
  { id: 'e-server-cache-endpoint', from: 'server-cache', to: 'pages-data-endpoint', kind: 'data', label: 'stored posts/7.json' },
  { id: 'e-endpoint-router', from: 'pages-data-endpoint', to: 'pages-router', kind: 'data', label: '{ pageProps }', crossing: 'data' },
  { id: 'e-router-gip', from: 'pages-router', to: 'pages-product-page', kind: 'control', label: 'getInitialProps(ctx) in the tab' },
  { id: 'e-chunks-post-page', from: 'browser-chunks', to: 'pages-post-page', kind: 'data', label: 'posts/[id] chunk', crossing: 'code' },
  { id: 'e-router-pages-app', from: 'pages-router', to: 'pages-app', kind: 'control', label: 'set Component' },
  { id: 'e-pages-app-post', from: 'pages-app', to: 'pages-post-page', kind: 'data' },
  { id: 'e-pages-router-history', from: 'pages-router', to: 'browser-history', kind: 'control', label: 'pushState' }
]

const byId = new Map(EDGES.map((e) => [e.id, e]))

export function edgeById(id: string): Edge {
  const e = byId.get(id)
  if (!e) throw new Error(`unknown edge ${id}`)
  return e
}
